### ISSUE TITLE
Handle Keyframes

### ISSUE THREAD

**Issue by hundekoerper** [hundekoerper/regular-weasel#1]
This error happens when the css file contains keyframes:
```
TypeError: Cannot read property 'length' of undefined
    at readProperties (regular-weasel/readProperties.js:11:64)
    at regular-weasel/index.js:23:23
    at fs.js:334:14
    at FSReqWrap.oncomplete (fs.js:95:15)
```

cc @lassediercks

**Comment by lassediercks** [comment]
ah, sneaky

**Comment by hundekoerper** [comment]
it will now just ignore the @keyframe rules and won't give any errors
